language: python

addons:
  postgresql: "9.3"

python:
  – "2.7.5"

install:
  – pip install -r requirements.txt

before_script:
  - psql -c 'create database easy_donor;' -U balanced_django
  – python manage.py syncdb –migrate –noinput

script:
  – python manage.py test easy_donor