language: python
python:
  - "2.7.5"

install: "pip install -r requirements.txt"

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database easy_donor;' -U balanced_django

script:
  - python manage.py test easy_donor